spring:
  application:
    name: department-service
  zipkin:
    base-url: http://127.0.0.1:9411/
server:
  port: 8091
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
