server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
              
spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://127.0.0.1:9411/
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 8s
      discovery:
        locator:
          enabled: true
      routes:
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employee/**
        filters:
        - RewritePath=/employee/(?<path>.*), /$\{path}
        - name: CircuitBreaker
          args:
            name: employee-service
            fallbackuri: forward:/employeeServiceFallback
      - id: department-service
        uri: lb://department-service
        predicates:
        - Path=/department/**
        filters:
        - RewritePath=/department/(?<path>.*), /$\{path}
        - name: CircuitBreaker
          args:
            name: department-service
            fallbackuri: forward:/departmentServiceFallback
      - id: organization-service
        uri: lb://organization-service
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
        - name: CircuitBreaker
          args:
            name: organization-service
            fallbackuri: forward:/organizationServiceFallback       
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
