server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

spring:
  application:
    name: employee-service
  zipkin:
    base-url: http://127.0.0.1:9411/
    
